# Generated by Django 5.0.2 on 2025-01-03 01:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auction', '0013_orderloadstage_completed_orderunloadstage_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordertracking',
            options={'verbose_name': 'Геоточка', 'verbose_name_plural': 'Геоточки'},
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='latitude',
            field=models.FloatField(default=1, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='longitude',
            field=models.FloatField(default=1, verbose_name='Долгота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='api_auction.ordermodel', verbose_name='Заказ'),
        ),
        migrations.DeleteModel(
            name='OrderTrackingGeoPoint',
        ),
    ]
