# Generated by Django 5.0.2 on 2025-01-09 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auction', '0014_alter_ordertracking_options_ordertracking_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderoffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='orderoffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='api_auction.ordermodel', verbose_name='Заказ'),
        ),
    ]
