# Generated by Django 5.0.2 on 2024-08-27 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0013_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    max_length=100, verbose_name='Название тарифа')),
                ('price', models.DecimalField(decimal_places=2,
                 max_digits=10, verbose_name='Стоимость')),
                ('days_without_payment', models.IntegerField(
                    verbose_name='Количество дней без оплаты')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы Заказчик',
            },
        ),
        migrations.CreateModel(
            name='TransporterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    max_length=100, verbose_name='Название тарифа')),
                ('price', models.DecimalField(decimal_places=2,
                 max_digits=10, verbose_name='Стоимость')),
                ('win_percentage_fee', models.DecimalField(decimal_places=2,
                 max_digits=10, verbose_name='% от суммы выигранной перевозки')),
                ('days_without_payment', models.IntegerField(
                    verbose_name='Количество дней без оплаты')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы Перевозчик',
            },
        ),
        migrations.AddField(
            model_name='customercompany',
            name='balance',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name='Баланс компании'),
        ),
        migrations.AddField(
            model_name='transportercompany',
            name='balance',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name='Баланс компании'),
        ),
        migrations.AlterField(
            model_name='customercompany',
            name='allowed_transporter_companies',
            field=models.ManyToManyField(related_name='allowed_customer_companies',
                                         to='api_users.transportercompany', verbose_name='Перевозчики компании'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(choices=[('customer_company', 'Заказчик (компания)'), ('customer_manager', 'Заказчик (менеджер)'), ('transporter_company', 'Перевозчик (компания)'), (
                'transporter_manager', 'Перевозчик (менеджер)'), ('driver', 'Водитель'), ('super_admin', 'Супер админ')], max_length=20, verbose_name='Тип'),
        ),
        migrations.RemoveField(
            model_name='customercompany',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='transportercompany',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='OrderViewer',
        ),
    ]
