# Generated by Django 5.0.2 on 2024-08-27 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0014_customersubscription_transportersubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercompany',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_users.customersubscription', verbose_name='Тариф'),
        ),
        migrations.AddField(
            model_name='transportercompany',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_users.transportersubscription', verbose_name='Тариф'),
        ),
    ]
