# Generated by Django 5.0.2 on 2024-09-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0020_alter_customercompany_allowed_transporter_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercompany',
            name='allowed_transporter_companies',
            field=models.ManyToManyField(blank=True, default=[], related_name='allowed_customer_companies', to='api_users.transportercompany', verbose_name='Перевозчики компании'),
        ),
    ]
